### ISSUE TITLE
Make Client::get public

### ISSUE THREAD

**Issue by Samrose-Ahmed** [nooberfsh/prusto#28]
This method shouldn't be private, it is useful to be able to access full result for custom usecases. Happy to make PR, currently have to fork.

https://github.com/nooberfsh/prusto/blob/master/src/client.rs#L426

**Comment by Samrose-Ahmed** [comment]
Actually I misread, looks like it is public my bad.

**Comment by nooberfsh** [comment]
It makes sense, PR are welcomed.
