### ISSUE TITLE
An error occurred while connecting

### ISSUE THREAD

**Issue by groobyming** [nooberfsh/prusto#43]
When I follow the official documentation example to connect to an existing trino server, I get the following error

`HttpNotOk(401, "Basic authentication or X-Trino-User must be sent")`
<img width="929" alt="image" src="https://github.com/nooberfsh/prusto/assets/34335395/c3aecc82-3439-40a0-9ee8-53981c5f94b0">

Here is my code:
```
ClientBuilder::new(user, host).port(port as u16).build().map_err(|e| {
            CustomError::ConnectOtherErr {message: e.to_string()}
})
```

**Comment by nooberfsh** [comment]
Please provide trino server version and the full example code.

**Comment by groobyming** [comment]
> Please provide trino server version and the full example code.

@nooberfsh Thanks for your replay.

Trino version: 382

Example Code:
 ```
use prusto::{ClientBuilder, Presto};

  #[derive(Presto, Debug)]
    struct Foo {
        a: i64,
        b: f64,
        c: String,
    }
    #[tokio::test]
    async fn main() {
        let cli = ClientBuilder::new("user", "localhost")
            .port(8080)
            .catalog("iceberg")
            .build()
            .unwrap();

        let sql = "SELECT * FROM iceberg.iceberg_test.test_log  LIMIT 1";
        let result = cli.get_all::<Foo>(sql.to_string()).await.unwrap().into_vec();
    }
```

**Comment by nooberfsh** [comment]
I can see the server is running locally, can you confirm the server can be accessed through [trino-cli](https://trino.io/docs/current/client/cli.html) or other database tools, such as DataGrip or dbeaver.

**Comment by groobyming** [comment]
> I can see the server is running locally, can you confirm the server can be accessed through [trino-cli](https://trino.io/docs/current/client/cli.html) or other database tools, such as DataGrip or dbeaver.


The following error occurs when using the idea database tool:

<img width="807" alt="image" src="https://github.com/nooberfsh/prusto/assets/34335395/ca30d85f-c2e3-4a57-af96-b8a4dae06d3b">

**Comment by nooberfsh** [comment]
It seems there is some error message in the background. 
<img width="611" alt="image" src="https://github.com/nooberfsh/prusto/assets/6291629/f91ee396-bcef-4110-8636-dee34339120c">
Can you run some simple query to see whether it is actually working?

**Comment by groobyming** [comment]
@nooberfsh 
I believe the issue is caused by different request headers in the Presto and Trino clients.

【Presto headers】：
https://prestodb.io/docs/current/develop/client-protocol.html
<img width="1039" alt="image" src="https://github.com/nooberfsh/prusto/assets/34335395/5127a7c7-e9df-45f6-b6c7-1074b4dac030">


【Trino headers】：
https://trino.io/docs/current/develop/client-protocol.html
<img width="766" alt="image" src="https://github.com/nooberfsh/prusto/assets/34335395/7279beb1-1bed-4b2e-88ea-4af2b09be59b">


And In our project, we can only hardcode the Presto header.
https://github.com/nooberfsh/prusto/blob/master/src/presto_header.rs
<img width="806" alt="image" src="https://github.com/nooberfsh/prusto/assets/34335395/f7d09180-6a7d-49ec-83d1-ac0d39900c95">
Is there any way to customize this header?

**Comment by nooberfsh** [comment]
`prusto` has two set of headers which is defined in [header.rs](https://github.com/nooberfsh/prusto/blob/master/src/header.rs) and [presto_header.rs](https://github.com/nooberfsh/prusto/blob/master/src/presto_header.rs), the default headers is trino, the presto header can be enabled by the `presto` feature. 

As I said before,  can you run some simple query in the IDE to see whether it is actually working?

**Comment by groobyming** [comment]
> It seems there is some error message in the background. <img alt="image" width="611" src="https://private-user-images.githubusercontent.com/6291629/331493282-f91ee396-bcef-4110-8636-dee34339120c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5Mjk0ODUsIm5iZiI6MTcxNTkyOTE4NSwicGF0aCI6Ii82MjkxNjI5LzMzMTQ5MzI4Mi1mOTFlZTM5Ni1iY2VmLTQxMTAtODYzNi1kZWUzNDMzOTEyMGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTdUMDY1OTQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzBmNzJiZGMxMmU3ZDNhNTY0Y2EwODQ0ZTA3YzlkYjE5OTMwYjJiYjE5ODRlZjM3Nzk3NWQ4NGRhMzA3Y2VlMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.KFakkxz4usvAzFa5ovNhGDImiURe6bnYBM8d5lBziag"> Can you run some simple query to see whether it is actually working?

<img width="699" alt="image" src="https://github.com/nooberfsh/prusto/assets/34335395/1edd17d7-df2f-4b08-81d1-954aad5a7bd1">

when I disable presto feature, it works for me

**Comment by groobyming** [comment]
> `prusto` has two set of headers which is defined in [header.rs](https://github.com/nooberfsh/prusto/blob/master/src/header.rs) and [presto_header.rs](https://github.com/nooberfsh/prusto/blob/master/src/presto_header.rs), the default headers is trino, the presto header can be enabled by the `presto` feature.
> 
> As I said before, can you run some simple query in the IDE to see whether it is actually working?

<img width="333" alt="image" src="https://github.com/nooberfsh/prusto/assets/34335395/bb0c7327-22ba-4698-8910-6cc5620b961f">
