### ISSUE TITLE
How to define a generic return structure?

### ISSUE THREAD

**Issue by groobyming** [nooberfsh/prusto#44]
The `get_all` method requires that the generic type `T` must implement the Presto trait. This can be limiting; for example, when Trino queries table data in Hive, there might be tens of thousands of tables. Do I need to define tens of thousands of structs similar to the following first?

```
use prusto::{ClientBuilder, Presto};

#[derive(Presto, Debug)]
struct Foo {
    a: i64,
    b: f64,
    c: String,
}
```

**Comment by groobyming** [comment]
> The `get_all` method requires that the generic type `T` must implement the Presto trait. This can be limiting; for example, when Trino queries table data in Hive, there might be tens of thousands of tables. Do I need to define tens of thousands of structs similar to the following first?
> 
> ```
> use prusto::{ClientBuilder, Presto};
> 
> #[derive(Presto, Debug)]
> struct Foo {
>     a: i64,
>     b: f64,
>     c: String,
> }
> ```

#[tokio::main]
async fn main() {
    dotenv().ok();

    let user = var("USER").unwrap();
    let host = var("HOST").unwrap();
    let port = var("PORT").unwrap().parse().unwrap();
    let catalog = var("CATALOG").unwrap();
    let sql = var("SQL").unwrap();

    let cli = ClientBuilder::new(user, host)
        .port(port)
        .catalog(catalog)
        .build()
        .unwrap();

    let data = cli.get_all::<Row>(sql).await.unwrap().into_vec();

    for r in data {
        println!("{:?}", r)
    }
}

**Comment by nooberfsh** [comment]
`prusto` does not support some trino types yet, e.g. timestamp with timezone, when `prusto` see these unsupported types it just return `EmptyData`. The right way I think it should return some error instead.  You can `cast` the unsupported column into supported column as a workaround.

> It will lose the column names

You can use [split](https://github.com/nooberfsh/prusto/blob/496f0a83c93cb5679b842338422be773125b7c52/src/types/data_set.rs#L36) to retain column names and types.

**Comment by groobyming** [comment]
> `prusto` does not support some trino types yet, e.g. timestamp with timezone, when `prusto` see these unsupported types it just return `EmptyData`. The right way I think it should return some error instead. You can `cast` the unsupported column into supported column as a workaround.
> 
> > It will lose the column names
> 
> You can use [split](https://github.com/nooberfsh/prusto/blob/496f0a83c93cb5679b842338422be773125b7c52/src/types/data_set.rs#L36) to retain column names and types.

Thanks 😀
