### ISSUE TITLE
Disable underlying SSL Verification on reqwest.

### ISSUE THREAD

**Issue by nalindalxr** [nooberfsh/prusto#50]
is there a way to disable client SSL verification so that it can bypass invalid/self-signed SSL certificates?

**Comment by nooberfsh** [comment]
You can use [no_verify](https://github.com/nooberfsh/prusto/blob/c4af8e2cb1ff6df981d05dde8c21dbf869b20e96/src/client.rs#L72-L75).

**Comment by nalindalxr** [comment]
Thank you @nooberfsh !

**Comment by domnikl** [comment]
@nooberfsh could you please create a new release for it?
