### ISSUE TITLE
Basic auth support

### ISSUE THREAD

**Issue by shk3** [nooberfsh/prusto#51]
Our Trino server is protected by basic auth, and all requests would need to carry the basic auth headers to proceed.

It looks to me that when this library tries to make calls for next-uri path, it misses out the basic auth credentials. Namely, we seem to need the following lines in the `get_next` function as well.
https://github.com/nooberfsh/prusto/blob/e2655bacd93297c26b1cb4d2ac4e9c9827d0afa5/src/client.rs#L444-L450

Is this intentional or a bug that we want to fix? Thanks!

**Comment by nooberfsh** [comment]
The `next-uri ` is provided by the trino server, I think the uri contains the auth info.
Have you encounter any problems?

**Comment by shk3** [comment]
Yes, we are getting 401 Unauthorized on the next-uri calls. 

As for the auth info in the URL, are you referring to the slug and the token in the URL? From what the source code implies, this doesn't seem to be for auth purposes? https://github.com/trinodb/trino/blob/77aca720b06f29475d002a82652a0a6fa839daa8/core/trino-main/src/main/java/io/trino/dispatcher/QueuedStatementResource.java#L378-L380 https://github.com/trinodb/trino/blob/77aca720b06f29475d002a82652a0a6fa839daa8/core/trino-main/src/main/java/io/trino/server/protocol/Slug.java#L49-L53

In our case, we have a gateway server that stands in front of Trino for authentication though. Other clients like pyhive and trino-python-client have been carrying auth credentials to next-url calls as far as I know, so we haven't seen this issue with other clients.

**Comment by nooberfsh** [comment]
What's your trino version.

**Comment by nooberfsh** [comment]
I found go's client implementation carries auth credentials to next-url as well,  I think it is the right way. 
But it's weird that we didn't encounter this specific error in our environment.  Nevertheless I will add the auth
info to the next-url calls.

**Comment by nooberfsh** [comment]
Can you test against #52 to see if it's fix the auth issue?
